### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by alexis-** [bjsi/Random-Woz-Quote#1]
Would you like to transfer this repo to the SuperMemo organization ? I think this is justified as this relates to SuperMemo and could help other users discover your project. You would, of course, retain all accreditation.

No obligation, let me know.

**Comment by bjsi** [comment]
That sounds great, let me fix the code (it's a mess) and make the csv searchable. Then I will transfer the repo.

**Comment by bjsi** [comment]
I think there is a permission issue, it won't let me transfer the repo.
